### ISSUE TITLE
java.lang.ThreadGroup:uncaughtException when calling Window#synchronizeComponents() in the wrong thread

### ISSUE THREAD

**Issue by N3ROO** [N3ROO/BettercolorsEngine#10]
```
Exception in thread "AWT-EventQueue-0" [21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalStateException: Rendersystem called from wrong thread
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.mojang.blaze3d.systems.RenderSystem.assertThread(RenderSystem.java:76)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.client.MainWindow.logGlError(MainWindow.java:218)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.lwjgl.system.JNI.invokeI(Native Method)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.lwjgl.glfw.GLFW.glfwGetKeyScancode(GLFW.java:3371)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.nero.bettercolors.Bettercolors.lambda$new$0(Bettercolors.java:85)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.nero.bettercolors.engine.view.Window.synchronizeComponents(Window.java:1213)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.nero.bettercolors.engine.BettercolorsEngine.toggleModule(BettercolorsEngine.java:516)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.nero.bettercolors.core.modules.Panic.onToggle(Panic.java:42)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.nero.bettercolors.engine.module.Module.toggle(Module.java:89)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.nero.bettercolors.engine.view.Window.lambda$setupModulesActivationStatus$5(Window.java:435)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.Component.processMouseEvent(Component.java:6533)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.Component.processEvent(Component.java:6298)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.Container.processEvent(Container.java:2236)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.Component.dispatchEventImpl(Component.java:4889)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.Container.dispatchEventImpl(Container.java:2294)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.Component.dispatchEvent(Component.java:4711)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.Container.dispatchEventImpl(Container.java:2280)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.Component.dispatchEvent(Component.java:4711)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventQueue.access$500(EventQueue.java:97)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventQueue$3.run(EventQueue.java:709)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventQueue$3.run(EventQueue.java:703)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.security.AccessController.doPrivileged(Native Method)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventQueue$4.run(EventQueue.java:731)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventQueue$4.run(EventQueue.java:729)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.security.AccessController.doPrivileged(Native Method)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
[21:24:50] [AWT-EventQueue-0/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by N3ROO** [comment]
The issue is not related to the engine. However, here is a temp fix

```java
if (name.startsWith("Gui")) {
                if (name.startsWith("Gui")) {
    try {
        keybindButton.setText("Gui toggle key: " + Window.TOGGLE_KEY + "(" + this.keyNameFunc.getKeyName(Window.TOGGLE_KEY) + ")");
    } catch (IllegalStateException e) {
        // happens if the function is not working properly (glfw called in wrong context for example)
        if (BettercolorsEngine.DEBUG) {
            e.printStackTrace();
        }
    }
} else {
    for(Module module : MODULES){
        if (name.startsWith(module.getName())) {
            try {
                keybindButton.setText(
                        module.getName() + " toggle key: " + module.getToggleKey() + "(" + this.keyNameFunc.getKeyName(module.getToggleKey()) + ")"
                );
            } catch (IllegalStateException e) {
                // happens if the given function is not working properly (glfw called in wrong context for example)
                if (BettercolorsEngine.DEBUG) {
                    e.printStackTrace();
                }
            }
            break;
        }
    }
}
```

**Comment by N3ROO** [comment]
An other fix could be to add a function that sync the components as soon as it's possible. It could be something like `synchronizeComponentsAsap()`, and it will wait until the right context is found to sync the components (without blocking the code).

**Comment by N3ROO** [comment]
I'm dumb... this has nothing to do with the engine
